server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message?useSSL=false
    username:
    password:
  jpa:
    show-sql: true