server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message?useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
#security:
#  oauth2.resource.filter-order: 3
#  signing-key: MaYzkSjmkzPC57L
#  encoding-strength: 256
#  security-realm: Spring security
#  jwt:
#    client-id: testjwtclientid
#    client-secret: XY7kmzoNzl100
#    grant-type: password
#    scope-read: read
#    scope-write: write
#    resource-ids: jwtresourceid
#jwt:
#  secret: myKeySecret
#  expiration: 604800
#  header: Authorization
#  authorities-key: scopes
#  prefix: Bearer
twilio:
  account:
    sid: ACbe03aa0d879c5b2c212ac2456785881d
  auth:
    token: 53d670f0c0b161b6cb326081a265de55
  phone:
    number: +12488342566